name: Pull Request Tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "main" ]
jobs:
  test:
    name: Run Unit Tests
    runs-on: large-build-runner
    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v3

